repos:

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.15.7
  hooks:
  - id: ruff-format
    args: [--diff]
  - id: ruff-check

- repo: https://github.com/rhysd/actionlint
  rev: v1.7.11
  hooks:
    - id: actionlint
      args: [-pyflakes=, -ignore, SC2086.*Double quote]

- repo: https://github.com/astral-sh/uv-pre-commit
  # uv version.
  rev: 0.10.9
  hooks:
    # Update the uv lockfile
    - id: uv-lock

- repo: local
  hooks:
    - id: cog-readme
      name: Verify usage in readme
      entry: uv tool run --from cogapp cog --check --check-fail-msg "Usage in README.md needs to be updated; uv tool run --from cogapp cog -rUP -- README.md" --verbosity 1 -UP -- README.md
      language: system
      files: '^src/argparse_help_markdown.py$'
      types: [python]
      stages: [pre-commit]
      pass_filenames: false
