name: "publish"

on:
  push:
    tags:
      - 'v*'

jobs:

  build:
    name: "Build wheel"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-python@v6
        with:
          python-version: "3.x"

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v7

      - name: build
        run: uv build --wheel

      - name: smoketest
        run: uv tool run dist/argparse_help_markdown*.whl tests/data/example.py

      - uses: actions/upload-artifact@v7
        with:
          path: dist/
          name: python-package-distributions
          if-no-files-found: error

  github-release:
    name: Make github release
    runs-on: ubuntu-latest
    needs: [build]

    permissions:
      actions: write
      contents: write
      attestations: write

    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: true

      - uses: actions/download-artifact@v8
        with:
          name: python-package-distributions
          path: dist/

      - env:
          GH_TOKEN: ${{ github.token }}
          tag: ${{ github.ref_name }}
        run:
          gh release create "$tag" --verify-tag --generate-notes --fail-on-no-commits -- dist/*

  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    needs: [build]

    permissions:
      # IMPORTANT: this permission is mandatory for Trusted Publishing
      id-token: write

    steps:
      - uses: actions/download-artifact@v8
        with:
          name: python-package-distributions
          path: dist/

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

  update-readme:
    runs-on: ubuntu-latest
    needs: [github-release]

    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: true
          fetch-tags: true
          ref: main

      - run: uv tool run --from cogapp cog -rUP -- README.md
      - uses: stefanzweifel/git-auto-commit-action@v7
        with:
          branch: main
          commit_message: "cog README.md"
          file_pattern: README.md
